// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Polling.Infrastructure.Persistence;

#nullable disable

namespace Polling.Infrastructure.Migrations
{
    [DbContext(typeof(PollingDbContext))]
    partial class PollingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Polling.Domain.Aggregates.Questionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("Polling.Domain.Aggregates.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("Polling.Domain.Aggregates.Questionnaire", b =>
                {
                    b.OwnsMany("Polling.Domain.ValueObjects.Question", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("QuestionnaireId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("QuestionnaireId");

                            b1.ToTable("Question");

                            b1.WithOwner()
                                .HasForeignKey("QuestionnaireId");

                            b1.OwnsMany("Polling.Domain.ValueObjects.Option", "Options", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Label")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("QuestionId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("QuestionId");

                                    b2.ToTable("Option");

                                    b2.WithOwner()
                                        .HasForeignKey("QuestionId");
                                });

                            b1.Navigation("Options");
                        });

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Polling.Domain.Aggregates.Response", b =>
                {
                    b.OwnsMany("Polling.Domain.ValueObjects.Answer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("ResponseId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("QuestionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ResponseId", "QuestionId");

                            b1.ToTable("Answer");

                            b1.WithOwner()
                                .HasForeignKey("ResponseId");
                        });

                    b.OwnsOne("Polling.Domain.ValueObjects.Fingerprint", "Fingerprint", b1 =>
                        {
                            b1.Property<Guid>("ResponseId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("FingerprintHash");

                            b1.HasKey("ResponseId");

                            b1.ToTable("Responses");

                            b1.WithOwner()
                                .HasForeignKey("ResponseId");
                        });

                    b.Navigation("Answers");

                    b.Navigation("Fingerprint")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
